version: '{build}-{branch}'
image: ubuntu1804
platform: x64

install:
#- sh: sudo apt-get -y  install virtualbox
- sh: sudo apt -y  install vagrant

build_script:
- vagrant up
- vagrant ssh -c "uname -a"
test: off
